source 'https://rubygems.org/'

gemspec name: 'example'

gem 'puma'
gem 'rack-contrib', git: 'https://github.com/rack/rack-contrib.git'
gem 'qu-redis'

gem 'puck-example_dep', path: '../example_dep'

group :extra do
  gem 'rack-cache'
end

group :not_installed do
  gem 'rack-mini-profiler'
end

group :development do
  gem 'puck', path: '../../..'
  gem 'jruby-jars', '= 1.7.11'
  gem 'pry'
  gem 'rake'
end

group :test do
  gem 'rspec'
end