source 'https://rubygems.org/'

gem 'puma'
gem 'grape'
gem 'rack-contrib', git: 'https://github.com/rack/rack-contrib.git'
gem 'qu-redis'

group :extra do
  gem 'rack-cache'
end

group :development do
  gem 'puck', path: '../../..'
  gem 'jruby-jars', '= 1.7.4'
  gem 'pry'
end

group :test do
  gem 'rspec'
end