source 'https://rubygems.org/'

gem 'puma'
gem 'grape'
gem 'rack-contrib', git: 'git@github.com:rack/rack-contrib.git'

group :extra do
  gem 'rack-cache'
end

group :development do
  gem 'jruby-jars', "= #{JRUBY_VERSION}"
  gem 'pry'
end

group :test do
  gem 'rspec'
end